---
- hosts: 127.0.0.1
  vars_files:
    - zuul-params.yaml

  tasks:
    - name: Include variables from job_vars/{{ zuul_project | basename }}
      include_vars: "job_vars/{{ zuul_project | basename }}"
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}"
      when: job_type is defined
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ network_type }}
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ network_type }}"
      when: job_type is not defined and network_type is defined
      failed_when: False
      tags: always

    - name: Configure FibreChannel
      include: tasks/configure-fibrechannel.yaml
      with_items: "{{ groups['win2016-compute'] }}"
      when: job_type == "fc" and vsan_name is defined

- hosts: win2016-compute
  any_errors_fatal: true
  vars_files: 
    - zuul-params.yaml
    - group_vars/windows

  tasks:
    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}"
      failed_when: False
      tags: always

    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}-{{ job_type }}"
      when: job_type is defined
      failed_when: False
      tags: always

    - name: Include variables from group_vars/win2016-compute-{{ zuul_project | basename }}-{{ network_type }}
      include_vars: "group_vars/win2016-compute-{{ zuul_project | basename }}-{{ network_type }}"
      when: network_type is defined and job_type is not defined
      failed_when: False
      tags: always

    # Run sanity checks as early as possible
    - include: tasks/windows/sanity-checks.yaml
    - name: Install FS-iSCSITarget-Server
      win_feature:
        name: FS-iSCSITarget-Server
        state: present
      when: job_type == "iscsi" and job_type is defined

    - include: build-win2016.yaml
