- hosts: all
  gather_facts: no
  vars_file:
    - zuul-params.yaml

  tasks:

  - name: Wait for all VMs to be reachable
    wait_for_connection:
      delay: 3
      timeout: 600
      sleep: 15

  - name: Configure FibreChannel
    include: tasks/configure-fibrechannel.yaml
    with_items: "{{ groups['all'] }}"
    when: job_type == "fc" and vsan_name is defined

  - name: Wait for all VMs to be reachable
    wait_for_connection:
      delay: 3
      timeout: 60
      sleep: 15
