---
  - name: Include variables from job_vars/{{ zuul_project | basename }}
    include_vars: "job_vars/{{ zuul_project | basename }}"
    failed_when: False
    tags: always

  - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}
    include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}"
    failed_when: False
    when: job_type is defined
    tags: always

  - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ network_type }}
    include_vars: "job_vars/{{ zuul_project | basename }}-{{ network_type }}"
    failed_when: False
    when: job_type is not defined and network_type is defined
    tags: always

  - name: Turn off VMs
    os_server_action:
      action: stop
      server: "{{ hostvars[node].hostname }}"
    delegate_to: localhost

  - name: Get compute IP for VM
    shell: "openstack hypervisor show {{ hostvars[node].compute_host }} -c host_ip -f value"
    register: compute_ip
    delegate_to: localhost

  - name: Configure FibreChannel adapter
    shell: "/usr/local/bin/wsmancmd -s -H {{ compute_ip.stdout }} -a certificate -c {{ win_crt }} -k {{ win_key }}
            'powershell Add-VMFibreChannelHba -VMName {{ hostvars[node].compute_instance_name }} -SanName {{ vsan_name }}'"
    args:
      executable: /bin/bash
    delegate_to: localhost

  - name: Turn on VMs
    os_server_action:
      action: start
      server: "{{ hostvars[node].hostname }}"
    delegate_to: localhost