  - name: Make sure ubuntu user has access to /opt/stack
    file:
      path: /opt/stack
      state: directory
      recurse: yes
      owner: ubuntu
      group: ubuntu
      mode: '0755'
    become: True

- name: Install zuul venv package
  unarchive:
    src: "{{ zuul_venv_pkg }}"
    dest: /opt/stack
    remote_src: yes
  become: True
  tags: install-zuul
